WITH TRIPS AS (

    SELECT
    distinct
    RIDE_ID,
    RIDEABLE_TYPE,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
    start_statio_id AS START_STATION_ID,
    MEMBER_CSUAL AS MEMBER_CASUAL,
    TIMESTAMPDIFF(second,TO_TIMESTAMP(ENDED_AT), TO_TIMESTAMP(STARTED_AT)) as TRIP_DURATION_SECONDS

FROM {{source('demo','bike')}}

WHERE RIDE_ID != 'ride_id'

limit 10
    )

SELECT *

FROM TRIPS